apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: j2oqf3tfu-dotnet-basic
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe-dotnet-basic:fae63bd8c5e2e6c300338a3b750b06d07fbf8da1@sha256:3164c953f1786cbc32c2c493585fa252c308439fdcd7e0a9447c276f4e75bcb5
          name: container-image
